-- Funciones de prueba

-- search public Acts
USE `KRONOS`;
DROP procedure IF EXISTS searchAllActsPublish;
DELIMITER $$
USE `KRONOS`$$
create procedure searchAllActsPublish()
begin
select SESSIONTYPE, SESSIONDATE, URL, T_ACT.PUBLIC, ACTIVE from T_ACT where T_ACT.PUBLIC=1;
end$$
DELIMITER ; 

-- search public Act by year

USE `KRONOS`;
DROP procedure IF EXISTS searchAllActsPublishByYear;
DELIMITER $$
USE `KRONOS`$$
create procedure searchAllActsPublishYear(in _year int)
begin
select SESSIONTYPE, SESSIONDATE, URL, T_ACT.PUBLIC, ACTIVE from T_ACT where T_ACT.PUBLIC=1 
AND YEAR(T_ACT.SESSIONDATE) = _year;
end$$
DELIMITER ; 



-- search public Accords

USE `KRONOS`;
DROP procedure IF EXISTS searchAccordsessionDatePublish;
DELIMITER $$
USE `KRONOS`$$
create procedure searchAccordsessionDatePublish(in sessionDate date)
begin
select ACCNUMBER, INCORDATE, 
DEADLINE, SESSIONDATE, TYPE_ID,T_TYPE.DESCRIPTION AS TYPE_DESC, OBSERVATIONS, PUBLIC, NOTIFIED,  STATE,T_STATE.DESCRIPTION AS STATE_DESC,  T_ACCPDF.URL, T_ACCPDF.FINALRESPONSE AS FINALRESPONSE, T_ACCPDF.ISAPPROVED AS ISAPPROVED, T_ACCPDF.CAN_DELETE AS CAN_DELETE   from T_ACCORD, T_ACCPDF,T_STATE, T_TYPE where T_ACCORD.ACCNUMBER= T_ACCPDF.ACCORD AND T_ACCORD.STATE=T_STATE.ID AND T_ACCORD.TYPE_ID=T_TYPE.ID AND T_ACCORD.SESSIONDATE = sessionDate AND T_ACC0RD.PUBLIC=1;
end$$
DELIMITER ; 


USE `KRONOS`;
DROP procedure IF EXISTS searchAllAccordsPublish;
DELIMITER $$
USE `KRONOS`$$
create procedure searchAllAccordsPublish()
begin
select ACCNUMBER, INCORDATE, 
DEADLINE, SESSIONDATE, TYPE_ID,T_TYPE.DESCRIPTION AS TYPE_DESC, OBSERVATIONS, PUBLIC, NOTIFIED,  STATE,T_STATE.DESCRIPTION AS STATE_DESC,  T_ACCPDF.URL , T_ACCPDF.FINALRESPONSE AS FINALRESPONSE, T_ACCPDF.ISAPPROVED AS ISAPPROVED, T_ACCPDF.CAN_DELETE AS CAN_DELETE  from T_ACCORD, T_ACCPDF,T_STATE, T_TYPE where T_ACCORD.ACCNUMBER= T_ACCPDF.ACCORD AND T_ACCORD.STATE=T_STATE.ID AND T_ACCORD.TYPE_ID=T_TYPE.ID AND T_ACCORD.PUBLIC = 1;
end$$
DELIMITER ; 


